
name: Android release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - uses: actions/cache@v3.3.2

    - name: Retrieve keystore
      run: echo "${{ secrets.KEYSTORE_FILE }}" > keystore.jks.asc && gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD }}" --armor keystore.jks.asc > androidApp/keystore.jks

    - name: Build and release
      uses: maierj/fastlane-action@v3.0.0
      with:
        # The lane that should be executed.
        lane: release
        # The relative path from the project root directory to the subdirectory where the fastlane folder is located.
        subdirectory: androidApp
