
name: Android build APK

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3.3.2
      with:
        key: "android"
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        working-directory: androidApp/

    - name: Retrieve keystore
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > androidApp/keystore.jks

    - name: Build and release
      uses: maierj/fastlane-action@v3.0.0
      with:
        # The lane that should be executed.
        lane: apk
        # The relative path from the project root directory to the subdirectory where the fastlane folder is located.
        subdirectory: androidApp/

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: App
        path: androidApp/build/outputs/apk/release
